### ISSUE TITLE
Tasker or export

### ISSUE THREAD

**Issue by varazir** [marcolivierarsenault/PolarHeartRateApplication#19]
Hello, I like the app but would love to have tasker plugin so I could integrate the data from the app with my tasks or to read a CSV/JSON file on the fly.

**Comment by marcolivierarsenault** [comment]
Hi,
What do you propose exactly, do have time and competency to do it. I do not have much time to work on the app, but if you do it and it fit our goal we could integrate it.

**Comment by varazir** [comment]
Hello, thanks for the reply.

I don't know how to code and I have tried but it looks so messy to me. I
know abit of scripting bash in linux

Here is a tutorial how to use AutoShare and intents.
http://joaoapps.com/autoshare/intentbuilder/

What I like is to have a way to call your app and get the current value
from the pulse sensor.
It's maybe not the best way to do it but it's a workaround I guess.


Kind regards
Daniel


2016-01-01 16:17 GMT+01:00 Marc-Olivier Arsenault <notifications@github.com>
:

> Hi,
> What do you propose exactly, do have time and competency to do it. I do
> not have much time to work on the app, but if you do it and it fit our goal
> we could integrate it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcolivierarsenault/PolarHeartRateApplication/issues/19#issuecomment-168312752>
> .
>



-- 
Kind Regards/Mvh
Daniel Söderlund
+46 (0) 703 576 509

**Comment by varazir** [comment]
I think I can download the source and compile the app myself just need the code added.

**Comment by marcolivierarsenault** [comment]
Yes you should be able, 
But propose a pull request for your changes

**Comment by varazir** [comment]
First I need help adding the code for the autoshare support. If you don't have time I have to check with someone ells.

**Comment by varazir** [comment]
okay, no help here ?

**Comment by varazir** [comment]
okay thanks, then I have to find someone ells that willing to help me modify your code.
