### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [marcolivierarsenault/PolarHeartRateApplication#24]
Just wondering whether this app is still maintained, as there were no commits for over 2 years? If not, you might consider "archiving" the project (can be done from its settings here at Github, and can be undone there as well).

**Comment by IzzySoft** [comment]
@marcolivierarsenault ^^? With no answer, I assume this project is abandoned?

**Comment by IzzySoft** [comment]
Not even a simple yes/no/maybe, @marcolivierarsenault? Maybe to the first anniversary of this issue? 🙊

**Comment by PanderMusubi** [comment]
@marcolivierarsenault Would you consider adding me as maintainer for this repo t continue its development?

**Comment by marcolivierarsenault** [comment]
Hey folks, sorry for the delays, no this is not maintained anymore.

**Comment by PanderMusubi** [comment]
Thanks for adding me as collaborator. I will make a new release in 2020.
